# -*- coding: utf-8 -*-
"""model3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IrdoMRGWqQ3T-2CE2ZTihM3oZbyETPcu
"""

import torch
from torch import nn
from transformers import SegformerImageProcessor, SegformerForSemanticSegmentation
from PIL import Image
import matplotlib.pyplot as plt
import requests

# convenience expression for automatically determining device
device = (
    "cuda"  # Device for NVIDIA or AMD GPUs
    if torch.cuda.is_available()
    else "mps"  # Device for Apple Silicon (Metal Performance Shaders)
    if torch.backends.mps.is_available()
    else "cpu"
)

# Load models
image_processor = SegformerImageProcessor.from_pretrained("jonathandinu/face-parsing")
model = SegformerForSemanticSegmentation.from_pretrained("jonathandinu/face-parsing")
model.to(device)

# URL of the image to be processed
url = "https://avatars.mds.yandex.net/get-kinopoisk-image/4303601/56b44a82-caeb-48f9-b9d2-5deafaf202ca/1920x"
image = Image.open(requests.get(url, stream=True).raw)

# Run inference on image
inputs = image_processor(images=image, return_tensors="pt").to(device)
outputs = model(**inputs)
logits = outputs.logits  # Shape (batch_size, num_labels, ~height/4, ~width/4)

# Resize output to match input image dimensions
upsampled_logits = nn.functional.interpolate(logits,
                size=image.size[::-1], # H x W
                mode='bilinear',
                align_corners=False)

# Get label masks
labels = upsampled_logits.argmax(dim=1)[0]

# Move to CPU to visualize in matplotlib
labels_viz = labels.cpu().numpy()
plt.imshow(labels_viz)
plt.show()