# -*- coding: utf-8 -*-
"""model2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vDZRGo2ymrzmarob1RgDjPXfkUqpOKVi
"""

from transformers import pipeline
from PIL import Image
import requests
import matplotlib.pyplot as plt

# загрузка изображения
def loadimage(url, filename="temp.jpg"):
    try:
        response = requests.get(url, stream=True)  # загрузка по частям
        response.raise_for_status()  # проверка на ошибки
        with open(filename, "wb") as f:  # бинарное открытие для записи
            f.write(response.content)  # сохранение
        return Image.open(filename)  # возвращаем объект изображения
    except requests.exceptions.RequestException as e:
        print(f"Error downloading image: {e}")  # вывод ошибки
        return None  # возвращаем None, если ошибка

# Классификация эмоции
def classify_emotion(image):
    pipe = pipeline("image-classification", model="dima806/facial_emotions_image_detection")
    result = pipe(image)
    emotion = result[0]['label']
    return emotion

# Загрузка изображения
image_url = "https://avatars.mds.yandex.net/i?id=9d85a60f685ce9491b2a86382604f6fd_l-4077689-images-thumbs&n=13"
image = loadimage(image_url)

# Классификация эмоции и вывод
emotion = classify_emotion(image)

# Отображение изображения и эмоции
plt.imshow(image)
plt.axis('off')  # скрыть оси
plt.title(f"Predicted Emotion: {emotion}")
plt.show()